# Generated by Django 4.0.2 on 2022-02-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='profile_picture',
            field=models.ImageField(upload_to='profile_picture/'),
        ),
    ]
