# Generated by Django 4.0.2 on 2022-02-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_extenduser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extenduser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_picture/'),
        ),
    ]
